name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-dev.txt
    
    - name: Run tests
      run: |
        pytest tests/ --cov=src
    
    - name: Check code style
      run: |
        black --check src/
        flake8 src/
    
    - name: Get timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
      shell: bash
    
    - name: Build
      run: |
        python scripts/build.py ${{ runner.os }} ${{ env.timestamp }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jvman-${{ runner.os }}-${{ env.timestamp }}
        path: |
          release/**/*.exe
          release/**/*.zip
          release/**/*.dmg
          release/**/*.deb
          release/**/release.json 