name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-dev.txt
    
    - name: Get timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
      shell: bash
    
    - name: Get version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      shell: bash
    
    - name: Build release
      run: |
        python scripts/build.py ${{ runner.os }} ${{ env.timestamp }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/**/jvman-${{ env.version }}-windows-setup.exe
          release/**/jvman-${{ env.version }}-windows.zip
          release/**/jvman-${{ env.version }}-macos-setup.dmg
          release/**/jvman-${{ env.version }}-macos.zip
          release/**/jvman-${{ env.version }}-linux-setup.deb
          release/**/jvman-${{ env.version }}-linux.zip
          release/**/release.json
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 